spring.application.name=padmavati-medicals-backend
server.port=8080

app.frontend-root=${FRONTEND_ROOT:../frontend}
app.storage-root=${REQUEST_STORAGE_ROOT:../backend-data}

spring.web.resources.static-locations=file:${app.frontend-root}/
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=10MB
